#pragma once

#include <array>
#include <cstddef>
#include <string_view>

namespace hits {

enum class HitsColumn : std::size_t {
    WatchID = 0,
    JavaEnable = 1,
    Title = 2,
    GoodEvent = 3,
    EventTime = 4,
    EventDate = 5,
    CounterID = 6,
    ClientIP = 7,
    RegionID = 8,
    UserID = 9,
    CounterClass = 10,
    OS = 11,
    UserAgent = 12,
    URL = 13,
    Referer = 14,
    IsRefresh = 15,
    RefererCategoryID = 16,
    RefererRegionID = 17,
    URLCategoryID = 18,
    URLRegionID = 19,
    ResolutionWidth = 20,
    ResolutionHeight = 21,
    ResolutionDepth = 22,
    FlashMajor = 23,
    FlashMinor = 24,
    FlashMinor2 = 25,
    NetMajor = 26,
    NetMinor = 27,
    UserAgentMajor = 28,
    UserAgentMinor = 29,
    CookieEnable = 30,
    JavascriptEnable = 31,
    IsMobile = 32,
    MobilePhone = 33,
    MobilePhoneModel = 34,
    Params = 35,
    IPNetworkID = 36,
    TraficSourceID = 37,
    SearchEngineID = 38,
    SearchPhrase = 39,
    AdvEngineID = 40,
    IsArtifical = 41,
    WindowClientWidth = 42,
    WindowClientHeight = 43,
    ClientTimeZone = 44,
    ClientEventTime = 45,
    SilverlightVersion1 = 46,
    SilverlightVersion2 = 47,
    SilverlightVersion3 = 48,
    SilverlightVersion4 = 49,
    PageCharset = 50,
    CodeVersion = 51,
    IsLink = 52,
    IsDownload = 53,
    IsNotBounce = 54,
    FUniqID = 55,
    OriginalURL = 56,
    HID = 57,
    IsOldCounter = 58,
    IsEvent = 59,
    IsParameter = 60,
    DontCountHits = 61,
    WithHash = 62,
    HitColor = 63,
    LocalEventTime = 64,
    Age = 65,
    Sex = 66,
    Income = 67,
    Interests = 68,
    Robotness = 69,
    RemoteIP = 70,
    WindowName = 71,
    OpenerName = 72,
    HistoryLength = 73,
    BrowserLanguage = 74,
    BrowserCountry = 75,
    SocialNetwork = 76,
    SocialAction = 77,
    HTTPError = 78,
    SendTiming = 79,
    DNSTiming = 80,
    ConnectTiming = 81,
    ResponseStartTiming = 82,
    ResponseEndTiming = 83,
    FetchTiming = 84,
    SocialSourceNetworkID = 85,
    SocialSourcePage = 86,
    ParamPrice = 87,
    ParamOrderID = 88,
    ParamCurrency = 89,
    ParamCurrencyID = 90,
    OpenstatServiceName = 91,
    OpenstatCampaignID = 92,
    OpenstatAdID = 93,
    OpenstatSourceID = 94,
    UTMSource = 95,
    UTMMedium = 96,
    UTMCampaign = 97,
    UTMContent = 98,
    UTMTerm = 99,
    FromTag = 100,
    HasGCLID = 101,
    RefererHash = 102,
    URLHash = 103,
    CLID = 104,
};

inline constexpr std::size_t kHitsColumnCount = 105;

inline constexpr std::array<std::string_view, kHitsColumnCount> HitsColumnNames{
    "WatchID",
    "JavaEnable",
    "Title",
    "GoodEvent",
    "EventTime",
    "EventDate",
    "CounterID",
    "ClientIP",
    "RegionID",
    "UserID",
    "CounterClass",
    "OS",
    "UserAgent",
    "URL",
    "Referer",
    "IsRefresh",
    "RefererCategoryID",
    "RefererRegionID",
    "URLCategoryID",
    "URLRegionID",
    "ResolutionWidth",
    "ResolutionHeight",
    "ResolutionDepth",
    "FlashMajor",
    "FlashMinor",
    "FlashMinor2",
    "NetMajor",
    "NetMinor",
    "UserAgentMajor",
    "UserAgentMinor",
    "CookieEnable",
    "JavascriptEnable",
    "IsMobile",
    "MobilePhone",
    "MobilePhoneModel",
    "Params",
    "IPNetworkID",
    "TraficSourceID",
    "SearchEngineID",
    "SearchPhrase",
    "AdvEngineID",
    "IsArtifical",
    "WindowClientWidth",
    "WindowClientHeight",
    "ClientTimeZone",
    "ClientEventTime",
    "SilverlightVersion1",
    "SilverlightVersion2",
    "SilverlightVersion3",
    "SilverlightVersion4",
    "PageCharset",
    "CodeVersion",
    "IsLink",
    "IsDownload",
    "IsNotBounce",
    "FUniqID",
    "OriginalURL",
    "HID",
    "IsOldCounter",
    "IsEvent",
    "IsParameter",
    "DontCountHits",
    "WithHash",
    "HitColor",
    "LocalEventTime",
    "Age",
    "Sex",
    "Income",
    "Interests",
    "Robotness",
    "RemoteIP",
    "WindowName",
    "OpenerName",
    "HistoryLength",
    "BrowserLanguage",
    "BrowserCountry",
    "SocialNetwork",
    "SocialAction",
    "HTTPError",
    "SendTiming",
    "DNSTiming",
    "ConnectTiming",
    "ResponseStartTiming",
    "ResponseEndTiming",
    "FetchTiming",
    "SocialSourceNetworkID",
    "SocialSourcePage",
    "ParamPrice",
    "ParamOrderID",
    "ParamCurrency",
    "ParamCurrencyID",
    "OpenstatServiceName",
    "OpenstatCampaignID",
    "OpenstatAdID",
    "OpenstatSourceID",
    "UTMSource",
    "UTMMedium",
    "UTMCampaign",
    "UTMContent",
    "UTMTerm",
    "FromTag",
    "HasGCLID",
    "RefererHash",
    "URLHash",
    "CLID",
};

constexpr std::size_t Col(HitsColumn column) {
    return static_cast<std::size_t>(column);
}

constexpr std::string_view Name(HitsColumn column) {
    return HitsColumnNames[Col(column)];
}

} // namespace hits
